spring:
  profiles:
    active: dev
---
server:
  port: 8201
# spring配置
spring:
  profiles:
    active: dev
  application:
    name: springcloudproviderdept
# eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
---
server:
  port: 8202
# spring配置
spring:
  profiles:
    active: test
  application:
    name: springcloudproviderdept
# eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/